name: gazelle
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.9.1
  - torchvision
  - torchaudio
  - pytorch-cuda
  - timm
  - scikit-learn
  - matplotlib
  - pandas
  - opencv-python